### ISSUE TITLE
Crash on startup? (Godot 4.2 Stable)

### ISSUE THREAD

**Issue by WithinAmesia** [don-tnowe/godot-wyvernquest-rpg#3]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/ac802724-b3f3-4cfe-b50a-034ec7481255)
It failed to load a bunch of scenes its a fresh download .zip and I'm using Godot 4.2 stable and I tried the Godot 4.2 .net / C# support and I figured to just share this while I try to guess whats going on. I am sure there's a fix but I figured to share the bug openly and see if there's a cleaner fix than me just ramming stuff together until it works. Any recommendations? I hope its on my end being dumb for its an easy solution then. 4.2 Stable released on nov 30 and the projects is from Oct 19 and Godot said it was built with 4.2. So I didn't convert it and stopped and I used 4.2 and we are here. I remember Wyvernshield working so I wonder whats the issue?

**Comment by WithinAmesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/69c8ae49-59f1-47ad-996c-b5599a2bcbc0)
Maybe 4.2 is breaking it here's a fresh copy of wyvern triggers but let to convert to 4.2 and right out of the gate its errors. I'll try running Godot 4.1 on the 4.1 wyvern trigger to see if it still happens.

**Comment by WithinAmesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/083243d9-af09-4482-b57d-3fcfe765ae4b)
 safe save hmmm, this is old 4.1 with save wyvern-trigger but errors on start up

**Comment by WithinAmesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/3e1022a0-2fdf-40d1-a578-85013598e6bb)
still runs on Godot 4.1 and wyvernshield ~4.1

**Comment by WithinAmesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/cd7cebb3-b944-47a3-b7e6-3d25035c159e)
it works on Godot 4.1 and I got a fresh .zip and made a fresh folder and imported it and let it 'downgrade' from 4.2 to 4.1 and it works?

**Comment by WithinAmesia** [comment]
Did 4.2 break it and Wyvern Quest RPG was made with 4.1 or is my new 4.2 stable and 4.2 stable .net C# support Godot engines like not set up right or? I wonder why a fresh Wyvern Quest RPG refuses to run on a fresh Godot 4.2 stable and 4.2 .net C# support yet it works on Godot 4.1 stable and its says its 'downgraded' from 4.2 to 4.1 yet it was released before the stable version of 4.2 so was it built on an non stable version of 4.2 or something like hmmmm.

**Comment by don-tnowe** [comment]
It's on my end being dumb. It's a Wyvernshield bug that got fixed later. I will update all the addons.

**Comment by WithinAmesia** [comment]
It's okay I make bugs too, thank you for caring too.

**Comment by WithinAmesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/13009667/74ac0d9f-d21d-43ef-82db-8e56692ff2dc)
Working with 4.2.
