### ISSUE TITLE
Online Multiplayer, what steps are needed?

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernquest-rpg#4]
What is needed to make Godot 4.2.1 .NET online multiplayer work with the ARPG stuff? Can multiplayer be added later or does it have to be carefully built from the start bit by bit around online multiplayer support? Ideally I could get the ARPG combination game demo working then add online multiplayer support but I worry that perhaps Godot may require everything to be made at the start to support online multiplayer.

What is required to get multiplayer working beyond just local split screen but for hosting games with online multiplayer? https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html . I am hoping to avoid tech debt / retro-porting hell via responsible development planning but I am wondering if it makes sense to just hammer out a working single-player demo ARPG then add online multiplayer later? Or if its worth going all in at the start to do online multiplayer because adding online multiplayer later is quite difficult?

Should I just hammer out a single player demo with all the combined ARPG features and then just worry about getting it working with online multiplayer later or do I have to develop the single-player and online multiplayer support at the same time? Is there a way to test a mini Wyvern RPG with online multiplayer demo? Is online multiplayer Wyvern Quest RPG demo a good idea for people? I would like to believe in online multiplayer support. Online multiplayer adds so much life and longevity to games and Godot 4 has so much powerful online multiplayer networking support.

**Comment by WithinAmnesia** [comment]
https://www.youtube.com/watch?v=MOJVjFngOs4 I have a fresh slate so do I just build a test online game demo and try to make that into the ARPG to start with online multiplayer?

**Comment by WithinAmnesia** [comment]
https://www.youtube.com/watch?v=lk6kFiOYgaM I wonder if there is a demo Godot 4 project with online multiplayer support somewhere to reverse engineer?

**Comment by don-tnowe** [comment]
I only know multiplayer on a theoretical level, so I'm probably not one to know best 🤔

I plan on making games with online multiplayer support, but that's if I even get to doing that. Unless I actually do it, Wyvernshield and Wyvernbox are unlikely to get it in core.

You've found tutorials, so good luck!

**Comment by WithinAmnesia** [comment]
https://www.youtube.com/watch?v=ulfGNtiItnc I feel I should smash my face into this beehive for the both of us to get online multiplayer working for this kind of project. From like from a quick glance do you think this could support player saving at log out and like be ARPG feature compatible like multiple levels with players running around in-between them all at the same time?

As like I know Diablo 1 has online multiplayer and its from 1996-1997. So I hope I can smash out a demo online multiplayer game but I hope you can help me tweak and adjust stuff to get working like a ARPG / Wyvern RPG stuff but with online multiplayer support? I can ram through all the bugs and basic building I just need help with like some features like making it ~2D like Zelda / Diablo / Flare top down ARPG and like I know I'll make dumb bugs and errors along the way simply by just not having a lot of experience. Yet I can blast through the hard stuff to get a version 1.0 working and I think it can be iterated over time into an ARPG MIT forever free and all that.

I'll start working on this online multiplayer demo game in Godot 4 and try to smash it into an ARPG that works with the Wyvern ARPG and other ARPG content for Godot 4. Any important suggestions? I guess if I can pull this off its like a small MMORPG lol but lets be practical and start with just online multiplayer; 16 people within an online multiplayer ~2D ARPG would be a great success.

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/86871191/d79852cf-7932-4300-b408-a1b31e51d9d9)
Online multiplayer test success! Godot version 4.2.1.NET https://youtu.be/e0JLO_5UgQo?t=4253
https://github.com/finepointcgi/Godot-4-Multiplayer-Lan-Tutorial/tree/main
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/86871191/5311f72a-bee7-4dae-97c2-faf481f4c389)
Have the IP address be line 3 --->>@export var Address = "127.0.0.1"<<<--- to get the LAN working make sure the godot exporter is 2 instances like this: 
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/86871191/589aeb21-6d17-46f1-8aeb-9521de95a213)
Then press run scene or run current scene, this will bring up 2 stacked debug screens / windows, click hold and drag the first first off the second below stacked debug screen / window and click on the first debug screen / window "Host" then click on the second debug screen / window "Join" then click back to the first debug window / screen "Start Game". then it should launch both games instances and you can hover the mouse over click and aim and control the player character for each one. Controls are aim mouse around screen and gun with point at mouse and left click is shoot and arrow keys are move the player character around and space bar is to jump. Yay MIT license forever free Godot 4.2.1.NET working LAN and dedicated server online multiplayer game yaaaaaaaaa! Big progress time!

**Comment by WithinAmnesia** [comment]
https://github.com/expressobits/inventory-system/tree/demos this is great for an example of online multiplayer inventory; its like minecraft but in Godot 4.

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/86871191/fd93e3a0-00c5-485e-91ac-9017af8b4754)
here is the online multiplayer inventory system working

**Comment by WithinAmnesia** [comment]
https://github.com/godotengine/godot-demo-projects Also I just found this great examples with multiplayer too.

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernquest-rpg/assets/86871191/a6bd8667-1698-4ec8-8def-48feaacc0183)
The Godot 4 engine examples demo from https://github.com/godotengine/godot-demo-projects work relly good for starting out and tinkering. There is damage for a start too. This is the bomber demo example with online multiplayer https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber How do we add Wyvern systems to this to make the stats way better hmmmm? Big tinkering time.
